### PR TITLE
Touch-ups + statx and openat2

### PR DESCRIPTION
**Pull request by tkp1n**
While adding support for the v5.6 `io_uring` API surface to [tkp1n/IoUring](https://github.com/tkp1n/IoUring) I noticed some inconsistencies with my last PR (#50). I also found it weird to add support for `statx` and `openat2` via `io_uring` without the "normal syscalls" being supported in this library.

Changes in this PR:
- Fix io_uring documentation as well as a misspelled define `IOSQE_IO_ASYNC` -> `IOSQE_ASYNC `
- Add support for `statx` (including the structs `statx` and `statx_timestamp`)
- Add support for `openat2` (including the struct `open_how`)

Please excuse that this PR is a mix of everything...

### CODE REVIEW

**Comment by tkp1n** [comment]
I can't find the CI logs... the tests work on my machine<sup>TM</sup> but I guess being on kernel v5.6 / libc v 2.31 could be what's making them pass on my side.

@tmds Could you please re-trigger CI or point me towards the logs?

**Comment by tmds** [comment]
> @tmds Could you please re-trigger CI or point me towards the logs?

I think you can find them using the red cross? -> https://travis-ci.org/github/tmds/Tmds.LibC/builds/676918168?utm_source=github_status&utm_medium=notification

**Comment by tkp1n** [comment]
I swear the log was empty the minute after it failed... I guess Travis needed another minute to recover from my mistake...

[Ubuntu 16.04 is on kernel version 4.4](https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions) which is pre-`statx`. I'll exclude it from the tests for the time being... have you considered upgrading Travis to 18.04?

**Comment by tmds** [comment]
> Ubuntu 16.04 is on kernel version 4.4 which is pre-statx. I'll exclude it from the tests for the time being... have you considered upgrading Travis to 18.04?

You can exclude some things in the `TestEnvironment` class:

https://github.com/tmds/Tmds.LibC/blob/660edade00444515a1e2596f9627c5bc43e4f2e7/test/Tmds.LibC.Tests/TestEnvironment.cs#L157-L168

Alternatively, you can look at changing `.travis.yml` to 18.04 if you want.

I don't have a strong preference.

**Comment by tkp1n** [comment]
> You can exclude some things in the `TestEnvironment` class:

I did that for now and leave the decision to jump to 18.04 to you.

**Comment by tkp1n** [comment]
@tmds Travis seems happy now (even though it doesn't show up in this thread anymore... 😕): https://travis-ci.org/github/tmds/Tmds.LibC/builds/677222982

**Comment by tmds** [comment]
Travis has been acting up.
Thank you Nicolas!

**Pull request merged**
