### PR TITLE
Update io_uring

### PR DESCRIPTION
**Pull request by tkp1n**
Updates and corrects structs and constants following https://github.com/torvalds/linux/blob/master/include/uapi/linux/io_uring.h

### CODE REVIEW

**Comment by tmds** [comment]
Thanks for fixing the constants!

Looks like you need to add io_uring_files_update to https://github.com/tmds/Tmds.LibC/blob/8ff98fccbaaa6c73f128be1aeb6fc2ed6e2038fa/test/Tmds.LibC.Tests/StructTests.cs#L109 for CI to pass.

io_uring is getting more interesting by the day!

**Comment by tkp1n** [comment]
Gotcha, thanks for the hint!
 
> io_uring is getting more interesting by the day!

It is indeed... I have a very early draft of a `io_uring` based transport for kestrel ready here: https://github.com/tkp1n/IoUring

Will tweet and blog about it when its slightly more polished so stay tuned :)

I think kernel version 5.5 will be a good baseline to do `io_uring`-based networking on as it introduces nice things like `accept`, `connect` and async cancel.

**Comment by tmds** [comment]
> It is indeed... I have a very early draft of a io_uring based transport for kestrel ready here: https://github.com/tkp1n/IoUring
Will tweet and blog about it when its slightly more polished so stay tuned :)

I'm watching the repo :smile: 

I've been thinking about doing some experimentation at the `Socket` level. With io_uring, and also with APIs that are in earlier Linux versions (used by kestrel-linux-transport).

> 5.5 will be a good baseline

5.5 is a good baseline for io_uring.

**Comment by tmds** [comment]
> I've been thinking about doing some experimentation at the Socket level. With io_uring, and also with APIs that are in earlier Linux versions (used by kestrel-linux-transport).

I'll let you know when I set something up. Maybe you want to look into an io_uring implementation.

**Pull request merged**
